steps:
- id: 'pulsar-standalone'
  name: 'maven:3.9-amazoncorretto-17-debian'
  script: |
    #!/usr/bin/env sh
    apt-get update && apt-get install -yq wget procps
    wget https://archive.apache.org/dist/pulsar/pulsar-2.11.1/apache-pulsar-2.11.1-bin.tar.gz
    tar xvfz apache-pulsar-2.11.1-bin.tar.gz
    cd apache-pulsar-2.11.1
    bin/pulsar-daemon start standalone
    sleep 20
    bin/pulsar-admin brokers healthcheck
    cd /workspace
    mvn test
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'TOPIC_ID=${_TOPIC_ID}'


