steps:
# Uncomment to build a new image using more recent Pulsar version
#- id: 'pulsar-standalone'
#  name: gcr.io/cloud-builders/docker
#  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]

- id: 'run-tests'
  name: ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
  script: |
    #!/usr/bin/env bash
    /apache-pulsar-2.11.1/bin/pulsar-daemon start standalone
    sleep 20
    /apache-pulsar-2.11.1/bin/pulsar-admin brokers healthcheck
    mvn test
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'TOPIC_ID=${_TOPIC_ID}'

# Uncomment to build a new image using more recent Pulsar version
#images:
#- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
substitutions:
  _LOCATION: us-central1
  _REPOSITORY: pulsar
  _IMAGE: pulsar-standalone
