steps:
# Uncomment to build a new image using more recent Pulsar version
#- id: 'pulsar-standalone'
#  name: gcr.io/cloud-builders/docker
#  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]

- id: 'run-tests'
  name: ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
  script: |
    #!/usr/bin/env bash
    export PULSAR_HOME=/apache-pulsar-2.11.1/
    ${PULSAR_HOME}/bin/pulsar-daemon start standalone
    sleep 20
    ${PULSAR_HOME}/bin/pulsar-admin brokers healthcheck
    mvn clean package -DskipTests=true
    cp target/tz-pulsar-io-1.1-SNAPSHOT.nar ${PULSAR_HOME}/examples/
    cp -r src/test/resources/ ${PULSAR_HOME}/examples/
    ${PULSAR_HOME}/bin/pulsar-admin sinks localrun --sink-config-file ${PULSAR_HOME}/examples/resources/tz-pubsub-sink.yaml  --archive ${PULSAR_HOME}/examples/tz-pulsar-io-1.1-SNAPSHOT.nar &
    mvn test -Dtest=org.apache.pulsar.io.gcp.PubsubSinkTest
    ${PULSAR_HOME}/bin/pulsar-admin sources localrun --source-config-file ${PULSAR_HOME}/examples/resources/tz-pubsub-source.yaml  --archive ${PULSAR_HOME}/examples/tz-pulsar-io-1.1-SNAPSHOT.nar &
    mvn test -Dtest=org.apache.pulsar.io.gcp.PubsubSourceTest
  env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'TOPIC_ID=${_TOPIC_ID}'

# Uncomment to build a new image using more recent Pulsar version
#images:
#- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
substitutions:
  _LOCATION: us-central1
  _REPOSITORY: pulsar
  _IMAGE: pulsar-standalone
